FROM openjdk:17


ARG JAR_FILE=build/libs/api-server-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} app.jar

ENV SPRING_PROFILES_ACTIVE dev
ENV MONGO_HOST ${MONGO_HOST}
ENV MONGO_PORT ${MONGO_PORT}
ENV MONGO_RIOTDATA_DB ${MONGO_RIOTDATA_DB}
ENV MONGO_USERNAME ${MONGO_USERNAME}
ENV MONGO_PASSWORD ${MONGO_PASSWORD}
ENV MONGO_ADMIN_DB ${MONGO_ADMIN_DB}

ENTRYPOINT ["java", "-jar", "/app.jar"]

EXPOSE 8080
