spring:
  main:
    allow-bean-definition-overriding: true

#mongodb:
#  host: ${MONGO_HOST}
#  port: ${MONGO_PORT}
#  database: ${MONGO_RIOTDATA_DB}
#  username: ${MONGO_USERNAME}
#  password: ${MONGO_PASSWORD}
#  timeZone: Asia/Seoul
#  uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_RIOTDATA_DB}?timezone=Asia/Seoul
mongodb:
  primary:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_RIOTDATA_DB}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    timeZone: Asia/Seoul
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_RIOTDATA_DB}?timezone=Asia/Seoul
  secondary:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_STATISTICS_DB}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    timeZone: Asia/Seoul
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_STATISTICS_DB}?timezone=Asia/Seoul


springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: '/statistics/swagger-ui.html'
    enabled: true

logging:
  # MongoRepository logger setting
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com:
      mongodb: DEBUG

  # logger timezone setting
  pattern:
    dateformat: "\"yyyy-mm-dd't'hh:mm:ss.sssxxx\", Asia/Seoul"

# Batch Resource
batch:
  host: ${BATCH_HOST}
  port: ${BATCH_PORT}

# Riot API
riot:
  api-key: ${RIOT_API_KEY}


# dev properties
---
spring.config.activate.on-profile: dev

mongodb:
  primary:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_RIOTDATA_DB}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    timeZone: Asia/Seoul
    authenticationDatabase: ${MONGO_ADMIN_DB}
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_RIOTDATA_DB}?timezone=Asia/Seoul
  secondary:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_STATISTICS_DB}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    timeZone: Asia/Seoul
    authenticationDatabase: ${MONGO_ADMIN_DB}
    uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_STATISTICS_DB}?timezone=Asia/Seoul
