spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_RIOTDATA_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      timeZone: Asia/Seoul
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_RIOTDATA_DB}?timezone=Asia/Seoul

server:
  servlet:
    context-path: /statistics

# MongoRepository logger setting
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# Batch Resource
batch:
  host: ${BATCH_HOST}
  port: ${BATCH_PORT}

# Riot API
riot:
  api-key: ${RIOT_API_KEY}


# dev properties
---
spring.config.activate.on-profile: dev
spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_RIOTDATA_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      admin_db: ${MONGO_ADMIN_DB}
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_RIOTDATA_DB}?authSource=${MONGO_ADMIN_DB}
