name: API SERVER DEPLOY TO DEVSERVER

on: 
  push:            
    branches: develop
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: repository 내용 가져오기
        uses: actions/checkout@master
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: test
        run: |
          cd build/libs
          ls -al
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'linux/arm64, linux/arm64/v8'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}

      - name: Docker 이미지 pull 이후 down/up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DIR }}
            touch .env
            sudo echo "${{ secrets.DEV_ENV }}" > .env
            echo ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker stop ${{ secrets.IMAGE_NAME }}
            sudo docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}
            sudo docker run --rm -d --env-file .env -p 8080:8080 -i --name statistics-api-server ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG }}

